#!/bin/bash
# Setting permissions for www-data
sudo chown www-data:www-data editableConfigFile.json
sudo chown www-data:www-data -R fileCache/
sudo chown www-data:www-data -R Services/Apriori/wip/
sudo chown www-data:www-data -R Services/KPrototype/wip/
sudo chown www-data:www-data -R Services/DBScan/wip/
