<?php
$configContent = array(
    'dataSource' => 'rapidminerdata.csv',
    'pageSize' => 10,
    'paginationWindow' => 3,
    'booleanFields' => ['CAIRCOND','CPOOL','CBBQ','CSAUNA','CJACUZZI','CWASHMACHI','CPARKING','CDISHWASHE','CFIREPLACE','SCTV','SCBALCONY','PETS','SCNOSMOKE','INTERNET'],
    'integerFields' => ['QUAL','ROOMS','BEDROOMS'],
    'floatFields' => ['longitude', 'latitude'],
    'stringFields' => ['NREF'],
    'priceFields' => ['PRICES'],
    'distanceFields' => ['DIWATER','DISKI','DICENTER','DISEA','DILAKE', 'DIPUBT'],
    'idField' => 'id',
    'atLeastFilterFields' => ['ROOMS','BEDROOMS'],
    'fieldNameMapping' => [
        'ID' => 'Id',
        'NREF' => 'NREF',
        'PRICES' => 'Price',
        'QUAL' => 'Stars',
        'ROOMS' => 'Rooms',
        'BEDROOMS' => 'Bedrooms',
        'DIWATER' => 'Close to water',
        'DISKI' => 'Close to ski',
        'DICENTER' => 'Close to center',
        'DISEA' => 'Close to sea',
        'DILAKE' => 'Close to lake',
        'DIPUBT' => 'Close to public transport',
        'CAIRCOND' => 'Aircondition',
        'CPOOL' => 'Pool',
        'CBBQ' => 'BBQ',
        'CSAUNA' => 'Sauna',
        'CJACUZZI' => 'Jacuzzi',
        'CWASHMACHI' => 'Washmachine',
        'CPARKING' => 'Parking',
        'CDISHWASHE' => 'Dishwasher',
        'CFIREPLACE' => 'Fireplace',
        'SCTV' => 'TV',
        'PETS' => 'Pets',
        'SCBALCONY' => 'Balcony',
        'SCNOSMOKE' => 'Non Smoking',
        'INTERNET' => 'Internet',
        'longitude' => 'Longitude',
        'latitude' => 'Latitude',
    ],
    'filterButtonTitle' => 'Apply Fiters',
    'runButtonTitle' => 'Run analysis',
    'bookingsCountCap' => null, // Debugging only. int|null
    'ignoreFields' => ['SCTV'],
    'apriori' => [
        'minSup' => 0.4, // percentage
        'serviceOutput' => '/Services/Apriori/wip/status.htm',
        'servicePidFile' => '/Services/Apriori/wip/pid.txt',
        'serviceStopFile' => '/Services/Apriori/wip/stop.txt',
        'outputInterval' => 10, // Seconds
    ],
    'kprototype' => [
        'serviceOutput' => '/Services/KPrototype/wip/status.htm',
        'servicePidFile' => '/Services/KPrototype/wip/pid.txt',
        'serviceStopFile' => '/Services/KPrototype/wip/stop.txt',
        'outputInterval' => 10, // Seconds
        'gamma' => 1, // value between 0-1.
    ]
);