<?php
$configContent = array(
    'dataSource' => 'rapidminerdata.csv',
    'pageSize' => 10,
    'paginationWindow' => 3,
    'booleanFields' => ['CAIRCOND','CPOOL','CBBQ','CSAUNA','CJACUZZI','CWASHMACHI','CPARKING','CDISHWASHE','CFIREPLACE','SCTV','SCBALCONY','PETS','SCNOSMOKE','INTERNET'],
    'integerFields' => [],
    'floatFields' => [/*'longitude', 'latitude', */'QUAL','ROOMS','BEDROOMS','REPAX'],
    'stringFields' => ['NREF','country','region','place', 'CUCNTRY', 'CUORT'],
    'priceFields' => ['weeklyprice'],
    'distanceFields' => ['DIWATER','DISKI','DICENTER','DISEA','DILAKE', 'DIPUBT'],
    'dayOfWeekFields' => ['dayOfWeek'],
    'monthOfYearFields' => ['monthOfYear'],
    'floatFieldsBoundaries' => [
        'QUAL' => ['lowest' => 0.2, 'increment' => 0.2],
        'ROOMS' => ['lowest' => 0, 'increment' => 0.053],
        'BEDROOMS' => ['lowest' => 0.067, 'increment' => 0.067],
        'REPAX' => ['lowest' => 0, 'increment' => 0.033],
    ],
    'idField' => 'id',
    'atLeastFilterFields' => ['ROOMS','BEDROOMS'],
    'fieldNameMapping' => [
        'ID' => 'Id',
        'NREF' => 'NREF',
        'weeklyprice' => 'Weekly price',
        'QUAL' => 'Stars',
        'ROOMS' => 'Rooms',
        'BEDROOMS' => 'Bedrooms',
        'DIWATER' => 'Close to water',
        'DISKI' => 'Close to ski',
        'DICENTER' => 'Close to center',
        'DISEA' => 'Close to sea',
        'DILAKE' => 'Close to lake',
        'DIPUBT' => 'Close to public transport',
        'CAIRCOND' => 'Aircondition',
        'CPOOL' => 'Pool',
        'CBBQ' => 'BBQ',
        'CSAUNA' => 'Sauna',
        'CJACUZZI' => 'Jacuzzi',
        'CWASHMACHI' => 'Washmachine',
        'CPARKING' => 'Parking',
        'CDISHWASHE' => 'Dishwasher',
        'CFIREPLACE' => 'Fireplace',
        'SCTV' => 'TV',
        'PETS' => 'Pets',
        'SCBALCONY' => 'Balcony',
        'SCNOSMOKE' => 'Non Smoking',
        'INTERNET' => 'Internet',
        'longitude' => 'Longitude',
        'latitude' => 'Latitude',
        'country' => 'Object Country',
        'region' => 'Object Region',
        'place' => 'Object Place',
        'CUCNTRY' => 'Customer Country',
        'CUORT' => 'Customer Place',
        'REPAX' => 'Pax',
        'dayOfWeek' => 'Booking Weekday',
        'monthOfYear' => 'Booking Month',
    ],
    'filterButtonTitle' => 'Apply Fiters',
    'runButtonTitle' => 'Run analysis',
    'bookingsCountCap' => 100, // debugging only. int|null
    'ignoreFields' => ['NREF','SCTV'], // for apriori algorithm.
    'fileCacheDirectory' => '/fileCache/',
    'apriori' => [
        'serviceOutput' => '/Services/Apriori/wip/status.htm',
        'servicePidFile' => '/Services/Apriori/wip/pid.txt',
        'serviceStopFile' => '/Services/Apriori/wip/stop.txt',
        'minSup' => 0.4, // percentage
        'outputInterval' => 1, // seconds
    ],
    'kprototype' => [
        'serviceOutput' => '/Services/KPrototype/wip/status.htm',
        'servicePidFile' => '/Services/KPrototype/wip/pid.txt',
        'serviceStopFile' => '/Services/KPrototype/wip/stop.txt',
        'runButtonTitle' => 'Run K-Prototype',
        'outputInterval' => 10, // seconds
        'maxIterations' => 10,
    ],
    'dbscan' => [
        'serviceOutput' => '/Services/DBScan/wip/status.htm',
        'servicePidFile' => '/Services/DBScan/wip/pid.txt',
        'serviceStopFile' => '/Services/DBScan/wip/stop.txt',
        'runButtonTitle' => 'Run DBSCAN',
        'outputInterval' => 10, // seconds
        'radius' => 6,
        'minPoints' => 0.1, // percentage
    ],
    'gamma' => 1, // value between 0-1.
    'editableConfigFile' => 'editableConfigFile.json',
    'destinationFile' => 'destinations3.csv',
    'customerDestinationFile' => 'customer-destinations.csv',
);